-- Script generated by Redgate Compare v1.8.1.8422

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping carrier.INDEX_SECD';END$$;
DROP INDEX carrier."INDEX_SECD";
SET check_function_bodies = true;
