-- Script generated by Redgate Compare v1.8.1.8422

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping carrier.raise_warning()';END$$;
DROP PROCEDURE carrier.raise_warning();
SET check_function_bodies = true;
