-- Script generated by Redgate Compare v1.8.1.8422

SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating carrier.INDEX_SECD...';END$$;
CREATE INDEX "INDEX_SECD" ON carrier.flyway_schema_history USING btree (version);
SET check_function_bodies = true;
